version: '3.8'

services:
  postiz-backend:
    image: node:20-alpine
    container_name: postiz-backend
    working_dir: /app/apps/backend
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://redis:6379
      PRISMA_MIGRATE: ${PRISMA_MIGRATE}
    ports:
      - "3000:3000"
    command: sh -c "apk add --no-cache python3 make g++ cairo-dev pango-dev giflib-dev libjpeg-turbo-dev pixman-dev fontconfig-dev freetype-dev && npm cache clean --force && npm install && npm run dev:backend"
    depends_on:
      - db
      - redis

  postiz-frontend:
    image: node:20-alpine
    container_name: postiz-frontend
    working_dir: /app/apps/frontend
    volumes:
      - ./:/app
    ports:
      - "3001:3000"
    command: sh -c "apk add --no-cache python3 make g++ cairo-dev pango-dev giflib-dev libjpeg-turbo-dev pixman-dev fontconfig-dev freetype-dev && npm cache clean --force && npm install && npm run dev:frontend"

  db:
    image: postgres:13
    container_name: postiz-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
